from tkinter import *
import pyautogui
from PIL import Image,ImageTk
import time
main=Tk()
main.geometry("1200x600")
bg = PhotoImage(file="py123.png")
label1 = Label(main, image=bg)
theme=Label(main,text="py-expo 2022",bg="#005ec0",fg="white",font=("italic",26))
theme.place(x=900,y=180)
theme=Label(main,text="programmatically control",bg="#005ec0",fg="white",font=("italic",26))
theme.place(x=780,y=220)
theme=Label(main,text="keyboard and mouse ",bg="#005ec0",fg="white",font=("italic",26))
theme.place(x=800,y=265)
theme=Label(main,text="using python",bg="#005ec0",fg="white",font=("italic",26))
theme.place(x=920,y=305)
label1.place(x=0, y=0)
main.config(bg="pink")
def function1():
    youtube=Tk()
    youtube.geometry("700x400")
    title=Label(youtube,text="YOUTUBE AUTOMATION",fg="red" , font=("bold",14))
    title.pack()
    title = Label(youtube, text="channel name :",fg="red", font=("courier", 14))
    title.place(x=243,y=195)

    username=Entry(youtube, borderwidth=0,width=40)
    username.place(x=400,y=200)

    def youtubesub():
        pyautogui.moveTo(1250, 7, 1)
        pyautogui.doubleClick()
        pyautogui.moveTo(1243, 7, 1)
        pyautogui.click()
        time.sleep(0.5)
        pyautogui.click()
        # opening chrome
        pyautogui.moveTo(35, 135, 1)
        pyautogui.doubleClick()
        time.sleep(1.5)
        maxi = pyautogui.locateCenterOnScreen("maxi.png")
        pyautogui.click(maxi)
        pyautogui.moveTo(253, 50, 1)
        pyautogui.click()
        time.sleep(3)
        # opening youtube
        pyautogui.typewrite("youtube.com", 0.3)
        pyautogui.press("enter")
        time.sleep(5)
        # youtube channel
        pyautogui.typewrite("/" + username.get(), 0.3)
        pyautogui.press("enter")
        time.sleep(5)
        subscribe = pyautogui.locateOnScreen("subscribe.png")
        pyautogui.click(subscribe)
        time.sleep(2)
        pyautogui.moveTo(1243, 7, 1)
        pyautogui.click()
        time.sleep(2)
        pyautogui.alert("subscribed succesfully!!!", username.get())
    def youtubenotsub():
        pyautogui.moveTo(1250, 7, 1)
        pyautogui.doubleClick()
        pyautogui.moveTo(1243, 7, 1)
        pyautogui.click()
        time.sleep(0.5)
        pyautogui.click()
        # opening chrome
        pyautogui.moveTo(35, 135, 1)
        pyautogui.doubleClick()
        time.sleep(1.5)
        maxi = pyautogui.locateCenterOnScreen("maxi.png")
        pyautogui.click(maxi)
        pyautogui.moveTo(253, 50, 1)
        pyautogui.click()
        time.sleep(3)
        # opening youtube
        pyautogui.typewrite("youtube.com", 0.3)
        pyautogui.press("enter")
        time.sleep(5)
        # youtube channel
        pyautogui.typewrite("/" + username.get(), 0.3)
        pyautogui.press("enter")
        time.sleep(5)
        subscribe = pyautogui.locateOnScreen("unsubscribe.png")
        pyautogui.click(subscribe)
        time.sleep(4)
        pyautogui.moveTo(780, 450, 1.5)
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(1243, 7, 1)
        pyautogui.click()
        pyautogui.alert("unsubscribed succesfully!!!", username.get())


    button = Button(youtube, text="subscribe", bg="red", borderwidth=0,width=20,height=2, activebackground="blue",command=youtubesub)
    button.place(x=450, y=240)
    button1 = Button(youtube, text="unsubscribe", bg="red", borderwidth=0, width=20, height=2, activebackground="blue",
                    command=youtubenotsub)
    button1.place(x=450, y=300)

    youtube.mainloop()
def instamain():
    insta=Tk()
    insta.geometry("700x400")
    insta.config(bg="violet")
    title=Label(insta,text="INSTAGRAM AUTOMATION" ,bg="violet",fg="white", font=("bold",14))
    title.pack()
    pic = PhotoImage(file="C:\\Users\\VV\\progress_tracking\\client\\public\\yout123.png")
    piclab = Label(image=pic)
    title = Label(insta, text="user name", bg="violet",fg="black", font=("bold", 14,))
    title.place(x=300,y=190)
    title = Label(insta, text="password:", bg="violet",fg="black", font=("bold", 14,))
    title.place(x=300,y=220)
    username = Entry(insta, bg="white")
    username.place(x=400, y=200)
    password = Entry(insta, bg="white")
    password.place(x=400, y=230)
    def instacode():
        pyautogui.moveTo(1243, 7, 1)
        pyautogui.click()
        time.sleep(0.5)
        pyautogui.click()
        pyautogui.moveTo(35, 135, 1)
        pyautogui.doubleClick()
        time.sleep(1.5)
        maxi = pyautogui.locateCenterOnScreen("maxi.png")
        pyautogui.click(maxi)
        time.sleep(1)
        pyautogui.moveTo(253, 50, 1)
        pyautogui.click()
        time.sleep(3)
        pyautogui.typewrite("https://www.instagram.com/accounts/login/", 0.2)
        pyautogui.press("enter")
        time.sleep(3.5)
        pyautogui.moveTo(600, 240, 1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.typewrite(username.get(), 0.2)
        pyautogui.moveTo(600, 290, 1.2)
        pyautogui.click()
        pyautogui.typewrite(password.get(), 0.2)
        pyautogui.moveTo(600, 340, 1)
        pyautogui.click()

    button3 = Button(insta, text="login", bg="blue",fg="white", borderwidth=0, activebackground="blue",width=20,height=2,command=instacode)
    button3.place(x=400, y=320)
    def instacode1():
        sub=Tk()
        sub.geometry("300x300")
        title=Label(sub,text="FILE DETAILS",font=("courier",14))
        title.place(x=100,y=0)
        title1 = Label(sub, text="FILE PATH", font=("courier", 14))
        title1.place(x=0, y=100)
        filename = Entry(sub,width=25)
        filename.place(x=130, y=100)
        title2= Label(sub, text="CAPTION", font=("courier", 14))
        title2.place(x=0, y=130)
        discription= Entry(sub,width=25)
        discription.place(x=130, y=130)
        def upload():
            pyautogui.moveTo(1243, 7, 1)
            pyautogui.click()
            time.sleep(0.5)
            pyautogui.click()
            pyautogui.moveTo(35, 135, 1)
            pyautogui.doubleClick()
            time.sleep(1.5)
            maxi = pyautogui.locateCenterOnScreen("maxi.png")
            pyautogui.click(maxi)
            time.sleep(1)
            pyautogui.moveTo(253, 50, 1)
            pyautogui.click()
            time.sleep(3)
            pyautogui.typewrite("https://www.instagram.com/accounts/login/", 0.2)
            pyautogui.press("enter")
            time.sleep(3.5)
            pyautogui.moveTo(600, 240, 1)
            pyautogui.click()
            time.sleep(1)
            pyautogui.typewrite(username.get(), 0.2)
            pyautogui.moveTo(600, 290, 1.2)
            pyautogui.click()
            pyautogui.typewrite(password.get(), 0.2)
            pyautogui.moveTo(600, 340, 1)
            pyautogui.click()
            time.sleep(6)
            file = pyautogui.locateCenterOnScreen("addfile.png")
            pyautogui.click(file)
            time.sleep(2.5)
            selectfile = pyautogui.locateCenterOnScreen("selectfile.png")
            pyautogui.click(selectfile)
            time.sleep(2)
            pyautogui.typewrite(filename.get(), 0.2)
            pyautogui.press("enter")
            # ratio bal
            time.sleep(2)
            next1 = pyautogui.locateCenterOnScreen("next1.png")
            pyautogui.click(next1)
            time.sleep(2.5)
            next2 = pyautogui.locateCenterOnScreen("next2.png")
            pyautogui.click(next2)
            time.sleep(2)
            pyautogui.moveTo(852, 337, 1)
            pyautogui.click()
            pyautogui.typewrite(discription.get(), 0.2)
            time.sleep(2)
            share = pyautogui.locateCenterOnScreen("share.png")
            pyautogui.click(share)
        button4 = Button(sub, text="click", bg="red", borderwidth=0, activebackground="blue", command=upload)
        button4.place(x=180, y=180)
        sub.mainloop()
    button = Button(insta, text="file", bg="blue", borderwidth=0,fg="white", activebackground="blue",width=20,height=2, command=instacode1)
    button.place(x=400, y=270)
    insta.mainloop()
pic=PhotoImage(file="C:\\Users\\VV\\Downloads\\you1234.png")
piclab=Label(image=pic)
button=Button(main,image=pic ,fg="pink",borderwidth=0,command=function1)
button.place(x=100,y=200)
pic2=PhotoImage(file="C:\\Users\\VV\\Downloads\\insta002.png")
pi2lab=Label(image=pic2)
button=Button(main,image= pic2,borderwidth=0,bg="blue",command=instamain)
button.place(x=310,y=210)
main.mainloop()
